common:
  env: "local"
  server:
    rest_prefix: "/api/cards"
    version: 1
    rest_port: ":8080"
    grpc_port: ":50051"
    shutdown_timeout: 5s
    cors:
      allowed_origins:
        - "https://kosarev.app"
      allow_credentials: true
      max_age: 86400
  sso:
    host_address: "sso:50052"
    use_local: false
    local_user_id: 0
open_telemetry:
  tracing:
    always_sample: false
    service_name: "lc-cards"
    trace_grpc_exporter_endpoint: "jaeger:4317"
database:
  connection_string_key: "DB_DNS"
  ping_duration: 5s
japanese_reading:
  search_timeout: 5s
  mecab_dic_dir: "/var/lib/mecab/dic/debian"