env: "local"
server:
  rest_prefix: "/api/learning-cards"
  rest_port: ":8080"
  grpc_port: ":50051"
sso:
  #  idea test (for debug)
  #  host_address: "localhost:50052"
  # container
  host_address: "sso:50052"
  use_local: true # true only for test local
  local_user_id: 0