services:
  postgres:
    image: postgres:16.3
    container_name: cards-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT_INTERNAL}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - net

  cards:
    container_name: cards-server
    image: ${IMAGE_NAME:-learning-cards:local}
    volumes:
      - ./.env:/app/.env
      - ./config.yaml:/app/config.yaml
    build:
      context: ../..
      dockerfile: cmd/cards/Dockerfile
      target: cards
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
      - "${REST_PORT}:${REST_PORT}"
    working_dir: /app
    environment:
      DB_URL: "${DB_DNS}"
      GRPC_PORT: ${GRPC_PORT}
      REST_PORT: ${REST_PORT}
    depends_on:
      postgres:
        condition: service_healthy
    command: ["./cards"]
    networks:
      - net

volumes:
  postgres_data:

networks:
  net:
    external: true
    name: iamvkosarev_network