services:
  postgres:
    image: postgres:16.3
    container_name: cards-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT_INTERNAL}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - net
  jaeger:
    image: jaegertracing/all-in-one:1.71.0
    container_name: jaeger
    ports:
      - "16686:16686"
      - "14250:14250"
      - "4317:4317"
      - "4318:4318"
    environment:
      - LOG_LEVEL=debug
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:16686" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - net
  redis:
    image: redis:7.4-alpine
    container_name: redis
    command: ["redis-server","--appendonly","yes"]
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - net
    restart: unless-stopped
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "PING" ]
      interval: 5s
      timeout: 3s
      retries: 5
  cards:
    container_name: cards-server
    image: ${IMAGE_NAME:-learning-cards:local}
    volumes:
      - ./.env:/app/.env
      - ./config.yaml:/app/config.yaml
    build:
      context: ../..
      dockerfile: cmd/cards/Dockerfile
      target: cards
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
      - "${REST_PORT}:${REST_PORT}"
    working_dir: /app
    environment:
      DB_URL: "${DB_DNS}"
      GRPC_PORT: ${GRPC_PORT}
      REST_PORT: ${REST_PORT}
    depends_on:
      postgres:
        condition: service_healthy
      jaeger:
        condition: service_healthy
      redis:
        condition: service_started
    command: [ "/cards" ]
    networks:
      - net

volumes:
  postgres_data:
  redis-data:

networks:
  net:
    external: true
    name: iamvkosarev_network
