services:
  learning-cards:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051" # gRPC
      - "8080:8080"   # REST
    working_dir: /app
    command: ["./server"]