// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.1
// source: learning_cards/v1/learning-cards.proto

package learning_cards

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCardsGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupName     string                 `protobuf:"bytes,1,opt,name=groupName,proto3" json:"groupName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCardsGroupRequest) Reset() {
	*x = CreateCardsGroupRequest{}
	mi := &file_learning_cards_v1_learning_cards_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardsGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardsGroupRequest) ProtoMessage() {}

func (x *CreateCardsGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_learning_cards_v1_learning_cards_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardsGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateCardsGroupRequest) Descriptor() ([]byte, []int) {
	return file_learning_cards_v1_learning_cards_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCardsGroupRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

type CreateCardsGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCardsGroupResponse) Reset() {
	*x = CreateCardsGroupResponse{}
	mi := &file_learning_cards_v1_learning_cards_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardsGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardsGroupResponse) ProtoMessage() {}

func (x *CreateCardsGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_learning_cards_v1_learning_cards_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardsGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateCardsGroupResponse) Descriptor() ([]byte, []int) {
	return file_learning_cards_v1_learning_cards_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCardsGroupResponse) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

var File_learning_cards_v1_learning_cards_proto protoreflect.FileDescriptor

const file_learning_cards_v1_learning_cards_proto_rawDesc = "" +
	"\n" +
	"&learning_cards/v1/learning-cards.proto\x12\x0elearning_cards\x1a\x1cgoogle/api/annotations.proto\"7\n" +
	"\x17CreateCardsGroupRequest\x12\x1c\n" +
	"\tgroupName\x18\x01 \x01(\tR\tgroupName\"4\n" +
	"\x18CreateCardsGroupResponse\x12\x18\n" +
	"\agroupId\x18\x01 \x01(\x03R\agroupId2\xa6\x01\n" +
	"\rLearningCards\x12\x94\x01\n" +
	"\x10CreateCardsGroup\x12'.learning_cards.CreateCardsGroupRequest\x1a(.learning_cards.CreateCardsGroupResponse\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/api/learning-cards/v1/cards/groupBRZPgithub.com/iamvkosarev/learning-cards/pkg/proto/learning_cards/v1;learning_cardsb\x06proto3"

var (
	file_learning_cards_v1_learning_cards_proto_rawDescOnce sync.Once
	file_learning_cards_v1_learning_cards_proto_rawDescData []byte
)

func file_learning_cards_v1_learning_cards_proto_rawDescGZIP() []byte {
	file_learning_cards_v1_learning_cards_proto_rawDescOnce.Do(func() {
		file_learning_cards_v1_learning_cards_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_learning_cards_v1_learning_cards_proto_rawDesc), len(file_learning_cards_v1_learning_cards_proto_rawDesc)))
	})
	return file_learning_cards_v1_learning_cards_proto_rawDescData
}

var file_learning_cards_v1_learning_cards_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_learning_cards_v1_learning_cards_proto_goTypes = []any{
	(*CreateCardsGroupRequest)(nil),  // 0: learning_cards.CreateCardsGroupRequest
	(*CreateCardsGroupResponse)(nil), // 1: learning_cards.CreateCardsGroupResponse
}
var file_learning_cards_v1_learning_cards_proto_depIdxs = []int32{
	0, // 0: learning_cards.LearningCards.CreateCardsGroup:input_type -> learning_cards.CreateCardsGroupRequest
	1, // 1: learning_cards.LearningCards.CreateCardsGroup:output_type -> learning_cards.CreateCardsGroupResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_learning_cards_v1_learning_cards_proto_init() }
func file_learning_cards_v1_learning_cards_proto_init() {
	if File_learning_cards_v1_learning_cards_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_learning_cards_v1_learning_cards_proto_rawDesc), len(file_learning_cards_v1_learning_cards_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_learning_cards_v1_learning_cards_proto_goTypes,
		DependencyIndexes: file_learning_cards_v1_learning_cards_proto_depIdxs,
		MessageInfos:      file_learning_cards_v1_learning_cards_proto_msgTypes,
	}.Build()
	File_learning_cards_v1_learning_cards_proto = out.File
	file_learning_cards_v1_learning_cards_proto_goTypes = nil
	file_learning_cards_v1_learning_cards_proto_depIdxs = nil
}
