// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.1
// source: learning_cards/v1/review.proto

package learning_cards

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetReviewCardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	CardsCount    int32                  `protobuf:"varint,2,opt,name=cards_count,json=cardsCount,proto3" json:"cards_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReviewCardsRequest) Reset() {
	*x = GetReviewCardsRequest{}
	mi := &file_learning_cards_v1_review_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReviewCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReviewCardsRequest) ProtoMessage() {}

func (x *GetReviewCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_learning_cards_v1_review_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReviewCardsRequest.ProtoReflect.Descriptor instead.
func (*GetReviewCardsRequest) Descriptor() ([]byte, []int) {
	return file_learning_cards_v1_review_proto_rawDescGZIP(), []int{0}
}

func (x *GetReviewCardsRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GetReviewCardsRequest) GetCardsCount() int32 {
	if x != nil {
		return x.CardsCount
	}
	return 0
}

type GetReviewCardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*Card                `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReviewCardsResponse) Reset() {
	*x = GetReviewCardsResponse{}
	mi := &file_learning_cards_v1_review_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReviewCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReviewCardsResponse) ProtoMessage() {}

func (x *GetReviewCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_learning_cards_v1_review_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReviewCardsResponse.ProtoReflect.Descriptor instead.
func (*GetReviewCardsResponse) Descriptor() ([]byte, []int) {
	return file_learning_cards_v1_review_proto_rawDescGZIP(), []int{1}
}

func (x *GetReviewCardsResponse) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

type ReviewCardResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        int64                  `protobuf:"varint,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	CardAnswer    CardAnswer             `protobuf:"varint,2,opt,name=card_answer,json=cardAnswer,proto3,enum=learning_cards.v1.CardAnswer" json:"card_answer,omitempty"`
	Duration      *durationpb.Duration   `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewCardResult) Reset() {
	*x = ReviewCardResult{}
	mi := &file_learning_cards_v1_review_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewCardResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewCardResult) ProtoMessage() {}

func (x *ReviewCardResult) ProtoReflect() protoreflect.Message {
	mi := &file_learning_cards_v1_review_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewCardResult.ProtoReflect.Descriptor instead.
func (*ReviewCardResult) Descriptor() ([]byte, []int) {
	return file_learning_cards_v1_review_proto_rawDescGZIP(), []int{2}
}

func (x *ReviewCardResult) GetCardId() int64 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *ReviewCardResult) GetCardAnswer() CardAnswer {
	if x != nil {
		return x.CardAnswer
	}
	return CardAnswer_EASY
}

func (x *ReviewCardResult) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

type AddReviewResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	CardResults   []*ReviewCardResult    `protobuf:"bytes,2,rep,name=card_results,json=cardResults,proto3" json:"card_results,omitempty"`
	CheckDuration bool                   `protobuf:"varint,3,opt,name=check_duration,json=checkDuration,proto3" json:"check_duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddReviewResultsRequest) Reset() {
	*x = AddReviewResultsRequest{}
	mi := &file_learning_cards_v1_review_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddReviewResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReviewResultsRequest) ProtoMessage() {}

func (x *AddReviewResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_learning_cards_v1_review_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReviewResultsRequest.ProtoReflect.Descriptor instead.
func (*AddReviewResultsRequest) Descriptor() ([]byte, []int) {
	return file_learning_cards_v1_review_proto_rawDescGZIP(), []int{3}
}

func (x *AddReviewResultsRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *AddReviewResultsRequest) GetCardResults() []*ReviewCardResult {
	if x != nil {
		return x.CardResults
	}
	return nil
}

func (x *AddReviewResultsRequest) GetCheckDuration() bool {
	if x != nil {
		return x.CheckDuration
	}
	return false
}

var File_learning_cards_v1_review_proto protoreflect.FileDescriptor

const file_learning_cards_v1_review_proto_rawDesc = "" +
	"\n" +
	"\x1elearning_cards/v1/review.proto\x12\x11learning_cards.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1clearning_cards/v1/card.proto\x1a\x1clearning_cards/v1/enum.proto\x1a\x17validate/validate.proto\"\\\n" +
	"\x15GetReviewCardsRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12(\n" +
	"\vcards_count\x18\x02 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\n" +
	"cardsCount\"G\n" +
	"\x16GetReviewCardsResponse\x12-\n" +
	"\x05cards\x18\x01 \x03(\v2\x17.learning_cards.v1.CardR\x05cards\"\xa2\x01\n" +
	"\x10ReviewCardResult\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\x03R\x06cardId\x12>\n" +
	"\vcard_answer\x18\x02 \x01(\x0e2\x1d.learning_cards.v1.CardAnswerR\n" +
	"cardAnswer\x125\n" +
	"\bduration\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\bduration\"\xa3\x01\n" +
	"\x17AddReviewResultsRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12F\n" +
	"\fcard_results\x18\x02 \x03(\v2#.learning_cards.v1.ReviewCardResultR\vcardResults\x12%\n" +
	"\x0echeck_duration\x18\x03 \x01(\bR\rcheckDurationBRZPgithub.com/iamvkosarev/learning-cards/pkg/proto/learning_cards/v1;learning_cardsb\x06proto3"

var (
	file_learning_cards_v1_review_proto_rawDescOnce sync.Once
	file_learning_cards_v1_review_proto_rawDescData []byte
)

func file_learning_cards_v1_review_proto_rawDescGZIP() []byte {
	file_learning_cards_v1_review_proto_rawDescOnce.Do(func() {
		file_learning_cards_v1_review_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_learning_cards_v1_review_proto_rawDesc), len(file_learning_cards_v1_review_proto_rawDesc)))
	})
	return file_learning_cards_v1_review_proto_rawDescData
}

var file_learning_cards_v1_review_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_learning_cards_v1_review_proto_goTypes = []any{
	(*GetReviewCardsRequest)(nil),   // 0: learning_cards.v1.GetReviewCardsRequest
	(*GetReviewCardsResponse)(nil),  // 1: learning_cards.v1.GetReviewCardsResponse
	(*ReviewCardResult)(nil),        // 2: learning_cards.v1.ReviewCardResult
	(*AddReviewResultsRequest)(nil), // 3: learning_cards.v1.AddReviewResultsRequest
	(*Card)(nil),                    // 4: learning_cards.v1.Card
	(CardAnswer)(0),                 // 5: learning_cards.v1.CardAnswer
	(*durationpb.Duration)(nil),     // 6: google.protobuf.Duration
}
var file_learning_cards_v1_review_proto_depIdxs = []int32{
	4, // 0: learning_cards.v1.GetReviewCardsResponse.cards:type_name -> learning_cards.v1.Card
	5, // 1: learning_cards.v1.ReviewCardResult.card_answer:type_name -> learning_cards.v1.CardAnswer
	6, // 2: learning_cards.v1.ReviewCardResult.duration:type_name -> google.protobuf.Duration
	2, // 3: learning_cards.v1.AddReviewResultsRequest.card_results:type_name -> learning_cards.v1.ReviewCardResult
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_learning_cards_v1_review_proto_init() }
func file_learning_cards_v1_review_proto_init() {
	if File_learning_cards_v1_review_proto != nil {
		return
	}
	file_learning_cards_v1_card_proto_init()
	file_learning_cards_v1_enum_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_learning_cards_v1_review_proto_rawDesc), len(file_learning_cards_v1_review_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_learning_cards_v1_review_proto_goTypes,
		DependencyIndexes: file_learning_cards_v1_review_proto_depIdxs,
		MessageInfos:      file_learning_cards_v1_review_proto_msgTypes,
	}.Build()
	File_learning_cards_v1_review_proto = out.File
	file_learning_cards_v1_review_proto_goTypes = nil
	file_learning_cards_v1_review_proto_depIdxs = nil
}
